dist: trusty
language: python
python:
  - "3.4"
  - "3.5"
  - "3.6" 
addons:
  apt:
    packages:
    - python3-dbus # Make sure that all system deps for dbus are installed
    - libdbus-1-dev # Make sure that all system deps for dbus are installed
    - libdbus-glib-1-dev # Make sure that all system deps for dbus are installed

install:
  - pip install -r requirements.txt --no-deps
  - pip install coveralls 

script: coverage run --source pifi setup.py test

after_success:
    coveralls
