sudo: required
dist: trusty
language: python
python:
  - "3.4"
 # - "3.6" travis is broken with this one right now
addons:
  apt:
    packages:
    - python3-dbus # Make sure that all system deps for dbus are installed
    - libdbus-1-dev # Make sure that all system deps for dbus are installed
    - libdbus-glib-1-dev # Make sure that all system deps for dbus are installed
    - network-manager

before_install:
  - sudo service network-manager restart
install:
  - pip install .
  - pip install coveralls 

script: coverage run --source pifi setup.py test

after_success:
    coveralls
